# Generated by Django 3.1.3 on 2020-12-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201213_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
    ]
