# Generated by Django 3.1.3 on 2020-12-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201220_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(verbose_name='Publication date'),
        ),
    ]
