# Generated by Django 3.1.3 on 2020-12-24 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201224_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='date',
            new_name='pub_date',
        ),
    ]
