# Generated by Django 3.1.3 on 2020-12-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201224_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='full_text',
            new_name='text',
        ),
    ]
