# Generated by Django 3.1.3 on 2020-12-25 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20201224_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
