# Generated by Django 3.1.3 on 2020-12-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_training', models.CharField(max_length=50, verbose_name='Type of training')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(verbose_name='Publication date')),
            ],
            options={
                'verbose_name': 'Workouts',
                'verbose_name_plural': 'Workouts',
            },
        ),
    ]
