# Generated by Django 3.1.3 on 2020-12-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workouts_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouts',
            name='likes',
        ),
    ]
