# Generated by Django 3.1.3 on 2020-12-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_workouts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='anons',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='full_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='type_of_training',
            field=models.CharField(max_length=50),
        ),
    ]
