# Generated by Django 3.1.3 on 2020-12-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20201223_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
