# Generated by Django 3.1.3 on 2020-12-23 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20201223_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
