# Generated by Django 3.1.3 on 2020-12-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20201223_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouts',
            old_name='date',
            new_name='pub_date',
        ),
    ]
