# Generated by Django 3.1.3 on 2020-12-25 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_auto_20201225_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
